### PR TITLE
Update forTranslators.xml

### PR DESCRIPTION
**Pull request by Drakan1976**
Traducción al español. Translation to Spanish.

### CODE REVIEW

**Comment by alelast** [comment]
Please add Italian too and the possibility to import a route using a txt document.
I'm New so i don't know where ask something to implement

**Comment by crisperfx** [comment]
I have a dutch translated version the XML file. Ik heb een nederlandstalige vertaling van het XML bestand. Added in txt file.

[forTranslators DUTCH NL .txt](https://github.com/PokeBotPub/PokeBot-Android/files/485005/forTranslators.DUTCH.NL.txt)

**Comment by aureliecpz** [comment]
s Please turn on apllication Iphone

**Comment by JokoKenguru** [comment]
Will there be a translation bot on Russian language?*

**Pull request closed without merging**
